name = "TreeSitter"
uuid = "f42328cb-ece0-4cf2-995f-9e7abb27d006"
authors = ["Michael Hatherly <michaelhatherly@gmail.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
tree_sitter_jll = "695101d5-1b81-5434-9529-70430e482717"

[compat]
CEnum = "0.4, 0.5"
Libdl = "1"
julia = "1.6"
tree_sitter_jll = "0.25"
